// Re-export centralisé des icônes lucide utilisées dans l'app.
// Ne JAMAIS importer directement depuis lucide-react dans les pages.
export {
  Search,
  Heart,
  Home,
  User,
  MapPin,
  Bed,
  Bath,
  Maximize2,
  Phone,
  MessageCircle,
  Share2,
  ChevronLeft,
  ChevronRight,
  SlidersHorizontal,
  Bookmark,
  Calendar,
  Check,
  X,
  Plus,
  Minus,
  Building2,
  ShieldCheck,
  Sparkles,
  ArrowRight,
  Menu,
} from "lucide-react";
